name: wallpix
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  lottie: ^2.6.0
  dio: ^5.2.0+1
  gson: ^0.1.4
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.2.0
  injectable: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  page_transition: ^2.1.0
  flutter_svg: ^2.0.7
  persistent_bottom_nav_bar_v2: ^4.2.8

flutter:
  assets:
    - assets/lottie/
    - assets/images/
    - assets/svg/
    
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/font/HaloHandletter.otf
  uses-material-design: true
